class Dynamic_Roles {
	#include "Config_Officer.hpp"

	#include "Config_Rifleman.hpp"
	#include "Config_Medic.hpp"
	#include "Config_Engineer.hpp"
	#include "Config_TeamLeader.hpp"
	#include "Config_SquadLeader.hpp"

	#include "Config_Pilot.hpp"
	#include "Config_UAVOp.hpp"

	#include "Config_Crewman.hpp"
	#include "Config_Commander.hpp"
};

class Common_Arsenal {
	items[] = {
		"ACE_adenosine", "ACE_epinephrine", "ACE_morphine",
		"ACE_fieldDressing", "ACE_elasticBandage", "ACE_packingBandage", "ACE_quikclot",
		"ACE_bloodIV", "ACE_bloodIV_250", "ACE_bloodIV_500",
		"ACE_plasmaIV", "ACE_plasmaIV_250", "ACE_plasmaIV_500",
		"ACE_salineIV", "ACE_salineIV_250", "ACE_salineIV_500",
		"ACE_tourniquet", "ACE_splint",
		"ACE_surgicalKit",

		"ACE_Chemlight_HiBlue", "ACE_Chemlight_HiGreen", "ACE_Chemlight_HiRed", "ACE_Chemlight_HiWhite", "ACE_Chemlight_HiYellow", "ACE_Chemlight_UltraHiOrange",
		"Chemlight_blue", "Chemlight_green", "Chemlight_red", "Chemlight_yellow", "acc_flashlight_pistol", "ACE_Flashlight_XL50", "ACE_Flashlight_MX991", "ACE_Flashlight_KSF1",
		"ACE_Chemlight_IR", "ACE_Chemlight_Orange", "ACE_Chemlight_White", "ACE_Chemlight_Shield", "ACE_Chemlight_Shield_Blue", "ACE_Chemlight_Shield_Green", "ACE_Chemlight_Shield_Orange", "ACE_Chemlight_Shield_Red", "ACE_Chemlight_Shield_White", "ACE_Chemlight_Shield_Yellow",
		"ACE_HandFlare_Green", "ACE_HandFlare_Red", "ACE_HandFlare_White", "ACE_HandFlare_Yellow", "ACE_IR_Strobe_Item",
		"SmokeShell", "SmokeShellBlue", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "SmokeShellRed", "SmokeShellYellow",
		"rhs_mag_m67", "MiniGrenade","rhs_mag_an_m14_th3",

		"ACE_RangeTable_82mm", "ACE_artilleryTable", "ACE_RangeCard", "ACE_Tripod", "ACE_ATragMX", "ACE_SpareBarrel", "ACE_SpottingScope", "ACE_Kestrel4500",

		"ItemMap","ItemCompass", "ItemWatch", "ItemGPS", "ACE_Altimeter", "ACE_MapTools", "ACE_CableTie", "ACE_EarPlugs", "ACE_microDAGR", "ACE_DAGR",

		"ToolKit", "ACE_DefusalKit","ACE_wirecutter", "ACE_EntrenchingTool", "ACE_Clacker", "ACE_M26_Clacker", "MineDetector", "ACE_SpraypaintRed", "ACE_SpraypaintGreen", "ACE_SpraypaintBlue", "ACE_SpraypaintBlack",
		"ACE_rope12", "ACE_rope15", "ACE_rope18", "ACE_rope27", "ACE_rope36",

		"B_UavTerminal", "ACE_UAVBattery", "ACE_VectorDay", "ACE_Vector", "Laserdesignator", "Laserbatteries",

		"U_B_Wetsuit", "U_B_survival_uniform","V_RebreatherB", "G_B_Diving", "G_Diving",
		"U_B_PilotCoveralls",
		
		"V_Rangemaster_belt",

		"B_Carryall_cbr", "B_Kitbag_cbr", "B_AssaultPack_cbr", "B_LegStrapBag_coyote_F", "B_Parachute", "ACE_NonSteerableParachute",

		"DemoCharge_Remote_Mag",
		"SatchelCharge_Remote_Mag",
		"B_IR_Grenade",

		"ACE_NVG_Wide_Black",
		"ACE_NVG_Wide",
		"ACE_NVG_Wide_Green",
		"ACE_NVG_Gen4_Green",
		"ACE_NVG_Gen4",
		"ACE_NVG_Gen4_Black",

		"Binocular",
		"Laserdesignator",
		"Laserdesignator_03",
		"ACE_Vector",
		"ItemMap",
		"ItemCompass",
		"TFAR_anprc152",
		"ACE_Altimeter",
		"ItemWatch",
		"ItemGPS",
		"B_UavTerminal",

		"rhs_uniform_g3_aor2",
		"rhs_uniform_g3_blk",
		"rhs_uniform_g3_m81",
		"rhs_uniform_g3_mc",
		"rhs_uniform_g3_rgr",
		"rhs_uniform_g3_rgr",

		"rhsusf_spcs_ocp_teamleader",
		"rhsusf_spcs_ocp_teamleader_alt",
		"rhsusf_spcs_ocp_squadleader",
		"rhsusf_spcs_ocp_sniper",
		"rhsusf_spcs_ocp_saw",
		"rhsusf_spcs_ocp_rifleman",
		"rhsusf_spcs_ocp_rifleman_alt",
		"rhsusf_spcs_ocp_medic",
		"rhsusf_spcs_ocp_machinegunner",
		"rhsusf_spcs_ocp_grenadier",
		"rhsusf_spcs_ocp_crewman",
		"rhsusf_mbav_rifleman",
		"rhsusf_mbav_medic",
		"rhsusf_mbav_mg",
		"rhsusf_mbav_grenadier",
		"rhsusf_mbav_light",

		/*AMF_AIO Content
		"amf_JPC_01_MTP",
		"amf_JPC_01",
		"amf_jpc_02_MTP",
		"amf_jpc_02",
		"amf_JPC_03_MTP",
		"amf_JPC_03",
		"amf_DCS_01_MTP",
		"amf_DCS_01_RG",
		"amf_DCS_02_MTP",
		"amf_DCS_02",
		"amf_DCS_03_MTP",
		"amf_DCS_03",
		"amf_DCS_04_MTP",
		"amf_DCS_04_RG",
		"amf_DCS_05_MTP",
		"amf_DCS_05_RG",
		"AMF_rush24_01_MTP",
		"AMF_FELIN_BACKPACK_TAN_MEDIC",
		*/
		"TFAR_rt1523g_rhs",
		"TFAR_rt1523g_black",
		"TFAR_rt1523g_bwmod",
		"rhsusf_assault_eagleaiii_ocp",
		"B_rhsusf_B_BACKPACK",
		"rhsusf_falconii_mc",
		"rhsusf_assault_eagleaiii_coy",
		"rhsusf_falconii_coy",
		"UK3CB_B_Backpack_Pocket",
		"UK3CB_B_B_Backpack_Radio_Chem",
		"UK3CB_B_Backpack_Med",
		"B_Kitbag_cbr",
		"B_Kitbag_mcamo",
		"B_AssaultPack_cbr",
		"B_AssaultPack_mcamo",
		"rhsusf_opscore_aor2_pelt_nsw",
		"rhsusf_opscore_bk_pelt",
		"rhsusf_opscore_coy_cover_pelt",
		"rhsusf_opscore_fg_pelt",
		"rhsusf_opscore_mc_cover_pelt",
		"rhsusf_opscore_mc_cover_pelt_cam",
		"rhsusf_opscore_paint_pelt_nsw",
		"rhsusf_opscore_rg_cover_pelt",
		"rhsusf_opscore_ut_pelt",
		"rhsusf_opscore_ut_pelt_nsw",
		"rhsusf_protech_helmet_rhino",
		"rhsusf_protech_helmet",
		"UK3CB_G_Balaclava",
		"rhsusf_shemagh_tan",
		"rhsusf_shemagh2_tan",
		"rhsusf_shemagh_od",
		"rhsusf_shemagh2_od",
		"G_Bandanna_beast",

		"rhs_weap_mk18",
		"rhs_weap_mk18_KAC",
		"rhs_weap_mk18_KAC_d",
		"rhs_weap_mk17_STD",
		"rhs_weap_sr25_ec",
		"rhs_weap_m4a1_blockII",
		"rhs_weap_m4a1_blockII_M203",
		"rhs_weap_mk18_m320",
		"rhs_weap_M590_5RD",
		"rhs_weap_m40a5",
		"rhs_weap_m32",
		"rhs_weap_m249_pip_S_para",
		"rhs_weap_XM2010",
		"rhs_weap_m14ebrri",
		"rhs_weap_hk416d10",
		"rhs_weap_hk416d10_m320",
		"rhs_weap_hk416d145",
		"rhs_weap_hk416d145_m320",
		
		"rhsusf_acc_grip_m203_blk",
		"rhsusf_acc_acog_rmr",
		"rhsusf_acc_su230_mrds",
		"rhsusf_acc_eotech_552",
		"rhsusf_acc_compm4",
		"rhsusf_acc_g33_xps3",
		"optic_hamr",
		"rhsusf_acc_anpeq15side_bk",
		"rhsusf_acc_anpeq15side",
		"rhsusf_acc_nt4_black",
		"rhsusf_acc_rotex5_grey",

		"rhs_mag_30Rnd_556x45_M855A1_Stanag",
		"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
		"rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",
		"rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull_Tracer_Red",
		"rhsusf_5Rnd_762x51_AICS_m118_special_Mag",
		"rhsusf_10Rnd_762x51_m118_special_Mag",
		"rhsusf_acc_harris_swivel",
		"optic_lrps",
		"rhsusf_acc_leupoldmk4",
		"rhsusf_acc_premier_mrds",
		"rhsusf_20Rnd_762x51_SR25_m118_special_Mag",
		"rhsusf_20Rnd_762x51_SR25_m993_Mag",
		"rhs_mag_20Rnd_SCAR_762x51_m80a1_epr",
		"rhs_mag_20Rnd_SCAR_762x51_m61_ap",
		"rhsusf_20Rnd_762x51_m80_Mag",
		"rhsusf_20Rnd_762x51_m993_Mag",
		"rhsusf_weap_glock17g4",
		"rhsusf_weap_MP7A2_folded",
		"rhsusf_mag_40Rnd_46x30_FMJ",
		"rhsusf_mag_17Rnd_9x19_JHP",
		"acc_flashlight_pistol",
		"rhsusf_acc_omega9k",
		"rhs_weap_M320",
		"rhs_mag_M433_HEDP",
		"rhs_mag_m713_Red",
		"rhs_mag_m714_White",
		"rhs_mag_m715_Green",
		"ACE_40mm_Flare_ir",
		"ACE_40mm_Flare_red",
		"ACE_HuntIR_M203",
		"ACE_HuntIR_monitor",
		"rhsusf_acc_anpeq15",
		"rhsusf_acc_rvg_blk",
		"rhsusf_acc_tacsac_blk"
	};
};